{% set name = "sorl-thumbnail" %}
{% set version = "12.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 191b89c27ecb40b5c2a35549d557d17c4841c6aff439b2e17b938b91eea463b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools_scm
  run:
    - python >=3.4

test:
  imports:
    - sorl
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/sorl-thumbnail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A django thumbnail library

  description: |
    Thumbnails for Django

  doc_url: http://sorl-thumbnail.readthedocs.io/
  dev_url: https://github.com/jazzband/sorl-thumbnail

extra:
  recipe-maintainers:
    - kcemenike
